### ISSUE TITLE
Random error about extensions for frame

### ISSUE THREAD

**Issue by benonymus** [bfolkens/wind#1]
Hey,

Thanks for the great lib!

I am seeing this error sometimes: 

```
[error] GenServer #PID<0.2500.0> terminating
** (KeyError) key :extensions not found in: nil. If you are using the dot syntax, such as map.field, make sure the left-hand side of the dot is a map
    (mint_web_socket 1.0.3) lib/mint/web_socket/frame.ex:103: Mint.WebSocket.Frame.encode/2
    (wind 0.2.1) lib/wind.ex:122: Wind.send/4
    (xxxx 0.1.0) lib/wind/client.ex:99: XXXX.WebSocket.send_frame/2
    (stdlib 4.3) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:"$gen_cast", {:send, {:binary, <<31, 67, 182, 117, 1, 255, 255, 255, 255, 255, 255, 255, 231, 131, 1, 189, 86, 163, 16, 0, 1, 69, 130, 0, 0, 0, 252, 1, 91, 153, 80, 12, 169, 139, 167, 176, 50, 106, 1, 80, 118, 234, 0, 86, ...>>}}}
```

Am I doing something wrong?

This is my start_link:
```
  def start_link(session_id) do
    uri = URI.new!("wss://test")

    headers = [{"Authorization", "Token " <> "secret"}]

    params = [uri: uri, headers: headers, session_id: session_id]

    Wind.Client.start_link(__MODULE__, params, [])
  end
```

Generally speaking it is working, I am just wondering about the error.

I am sending the message like this: 
```
    Wind.Client.send(socket_pid, {:binary, chunk})
```

Thank you

**Comment by benonymus** [comment]
I think the error is because I am sending before the websocket is ready, but the pid is alive.
Any ideas how to work around this?

**Comment by bfolkens** [comment]
Hi @benonymus - sorry for the delay, was a bit busy there for a while.

Yes it looks like the connection isn't yet ready.  The error above looks like it's originating in a function that expects the websocket struct to not be nil.

You may want to wait until the `handle_connect/1` callback is called or the state contains `conn_info: {conn, ref, websocket}` where `not is_nil(websocket)`.

I'm patching some things that should help debugging an issue like this easier in the future.
