### ISSUE TITLE
Transport headers being set for unencrypted connections

### ISSUE THREAD

**Issue by xanderificnl** [bfolkens/wind#2]
Hello there,

Hope you're doing well. I wanted to chat about a little hiccup I've run into while trying to establish a connection with a non-SSL server. Specifically, in [wind/client.ex:76](https://github.com/bfolkens/wind/blob/master/lib/wind/client.ex#L76), I noticed that the option `http_opts.transport_opts.verify` is set, and it seems like this might be causing an argument error.

To help you get a better grasp of what's going on, I've attached the snippet of code needed to recreate the issue. It's pretty similar to the example given in the README. Also, I've tossed in some snippets from the log to give you the full picture.

I'm definitely planning to roll up my sleeves and look into the MatchError a bit later, but before I dive in, I thought it would be a good idea to touch base with you. Your insights would be super valuable as I think about putting together a pull request to sort this out.

Appreciate your time and any thoughts you might have!

##### Code for reproduction

```elixir
defmodule PulseRail.Client do
  use Wind.Client, ping_timer: 30_000

  def start_link(_args) do
    Wind.Client.start_link(__MODULE__,
      uri: URI.new!("ws://echo.websocket.events/.ws")
	  # uncomment the next line for some success:
      # http_opts: [protocols: [:http1], transport_opts: []]
    )
  end

  @impl true
  def handle_connect(state) do
    message = Jason.encode!(%{method: "SUBSCRIBE", params: ["btcusdt@aggTrade"], id: 1})
    {:reply, {:text, message}, state}
  end

  @impl true
  def handle_frame({:text, message}, state) do
    data = Jason.decode!(message)
    IO.inspect(data)

    {:noreply, state}
  end
end
```

##### With `verify: :verify_none`

```elixir
06:42:49.863 [debug] Connecting to ws://echo.websocket.events/.ws

06:42:50.052 [error] GenServer #PID<0.191.0> terminating
** (ArgumentError) argument error
    (kernel 8.5.4.1) gen_tcp.erl:221: :gen_tcp.connect/4
    (mint 1.5.1) lib/mint/core/transport/tcp.ex:41: Mint.Core.Transport.TCP.connect/3
    (mint 1.5.1) lib/mint/http1.ex:133: Mint.HTTP1.connect/4
    (wind 0.2.4) lib/wind.ex:40: Wind.connect/3
    (pulserail 0.1.0) deps/wind/lib/wind/client.ex:81: PulseRail.Client.handle_continue/2
    (stdlib 4.3.1.2) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.2) gen_server.erl:865: :gen_server.loop/7
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:continue, :connect}
State: %{conn_info: nil, opts: [uri: %URI{scheme: "ws", userinfo: nil, host: "echo.websocket.events", port: 80, path: "/.ws", query: nil, fragment: nil}]}
```

##### When we override `http_opts` and remove `verify: :verify_none`

```
06:42:13.865 [debug] Connecting to ws://echo.websocket.events/.ws
06:42:13.956 [debug] Connected
06:42:14.050 [debug] Upgrading to websocket

06:42:14.050 [error] GenServer #PID<0.197.0> terminating
** (MatchError) no match of right hand side value: {:ok, %Mint.HTTP1{host: "echo.websocket.events", port: 80, request: nil, streaming_request: nil, socket: #Port<0.7>, transport: Mint.Core.Transport.TCP, mode: :active, scheme_as_string: "http", requests: {[], []}, state: :open, buffer: "", proxy_headers: [], private: %{extensions: [], scheme: :ws, sec_websocket_key: "gixABUrnEbPVK8oPcdBhwQ=="}, log: false}, [{:status, #Reference<0.1996560276.1166278659.107749>, 101}, {:headers, #Reference<0.1996560276.1166278659.107749>, [{"connection", "Upgrade"}, {"upgrade", "websocket"}, {"sec-websocket-accept", "B3lATybhy/kB+Qc+SG3BUqXSgyg="}, {"via", "1.1 vegur"}]}, {:data, #Reference<0.1996560276.1166278659.107749>, <<129, 42, 101, 99, 104, 111, 46, 119, 101, 98, 115, 111, 99, 107, 101, 116, 46, 101, 118, 101, 110, 116, 115, 32, 115, 112, 111, 110, 115, 111, 114, 101, 100, 32, 98, 121, 32, 76, 111, 98, 46, ...>>}, {:done, #Reference<0.1996560276.1166278659.107749>}]}
    (pulserail 0.1.0) lib/pulse_rail/client.ex:143: PulseRail.Client.handle_info/2
    (stdlib 4.3.1.2) gen_server.erl:1123: :gen_server.try_dispatch/4
    (stdlib 4.3.1.2) gen_server.erl:1200: :gen_server.handle_msg/6
    (stdlib 4.3.1.2) proc_lib.erl:240: :proc_lib.init_p_do_apply/3
Last message: {:tcp, #Port<0.7>, <<72, 84, 84, 80, 47, 49, 46, 49, 32, 49, 48, 49, 32, 83, 119, 105, 116, 99, 104, 105, 110, 103, 32, 80, 114, 111, 116, 111, 99, 111, 108, 115, 13, 10, 67, 111, 110, 110, 101, 99, 116, 105, 111, 110, 58, 32, 85, ...>>}
State: %{conn_info: {%Mint.HTTP1{host: "echo.websocket.events", port: 80, request: %{body: nil, connection: [], content_length: nil, data_buffer: [], headers_buffer: [], method: "GET", ref: #Reference<0.1996560276.1166278659.107749>, state: :status, status: nil, transfer_encoding: [], version: nil}, streaming_request: nil, socket: #Port<0.7>, transport: Mint.Core.Transport.TCP, mode: :active, scheme_as_string: "http", requests: {[], []}, state: :open, buffer: "", proxy_headers: [], private: %{extensions: [], scheme: :ws, sec_websocket_key: "gixABUrnEbPVK8oPcdBhwQ=="}, log: false}, #Reference<0.1996560276.1166278659.107749>, nil}, opts: [uri: %URI{scheme: "ws", userinfo: nil, host: "echo.websocket.events", port: 80, path: "/.ws", query: nil, fragment: nil}, http_opts: [protocols: [:http1], transport_opts: []]]}
```

**Comment by bfolkens** [comment]
Hi @xanderificnl - it looks like `Mint.WebSocket.stream/2` is failing to match the with clause in `Wind.setup/3`, which then falls through and passes the failed match.  It looks like in this case the first stream request sends a `{:data, ...}` tuple in addition to the final `{:done, ...}`, which it doesn't expect.  I'll need to look into this a bit more to see what the best way to handle this is.  A quick patch would be to match on both and just discard the `{:data, ...}`, but of course that wouldn't be ideal in the long term given that the data message contains information we would want to pass along to the caller.

**Comment by xanderificnl** [comment]
> Hi @xanderificnl - it looks like `Mint.WebSocket.stream/2` is failing to match the with clause in `Wind.setup/3`, which then falls through and passes the failed match. It looks like in this case the first stream request sends a `{:data, ...}` tuple in addition to the final `{:done, ...}`, which it doesn't expect. I'll need to look into this a bit more to see what the best way to handle this is. A quick patch would be to match on both and just discard the `{:data, ...}`, but of course that wouldn't be ideal in the long term given that the data message contains information we would want to pass along to the caller.

That issue may be specific to the implementation of `echo.websocket.events` since I wasn't able to replicate it with the Websocket endpoint of my local OpenHAB instance. What did you think about the `no_verify` option causing non-SSL connections to raise as bad arguments?

**Comment by bfolkens** [comment]
Ok, interesting.  I'll make a patch for this case at least and continue investigating.  It looks like it's sending a control character and then "*echo.websocket.events sponsored by Lob.com".

**Comment by bfolkens** [comment]
I can't seem to repro the issue above anymore now on `master` so I think the underlying issue may have been the one from https://github.com/bfolkens/wind/issues/2#issuecomment-1693390744, especially since the failing match in the error included that extra frame.  Can you try your test case again and see if it still fails?  I tried again with your repro code and it seems to work now with that patch.

**Comment by bfolkens** [comment]
Oh nevermind, I see what you're saying - the first error 🤦🏻

**Comment by bfolkens** [comment]
After some further investigation, I was able to reduce this down to the following failing code:

```elixir
Mint.HTTP.connect(:http, "echo.websocket.events", 80, protocols: [:http1], transport_opts: [verify: :verify_none])
```

Which seems related to https://github.com/elixir-mint/mint/pull/315.  Based on how the Finch team handled it in https://github.com/sneako/finch/pull/134, it seems we should drop the default TLS options when :http is used.  Will prepare a patch shortly.

**Comment by xanderificnl** [comment]
> After some further investigation, I was able to reduce this down to the following failing code:
> 
> ```elixir
> Mint.HTTP.connect(:http, "echo.websocket.events", 80, protocols: [:http1], transport_opts: [verify: :verify_none])
> ```
> 
> Which seems related to [elixir-mint/mint#315](https://github.com/elixir-mint/mint/pull/315). Based on how the Finch team handled it in [sneako/finch#134](https://github.com/sneako/finch/pull/134), it seems we should drop the default TLS options when :http is used. Will prepare a patch shortly.

Yes, that's correct. I was going to send a PR, but it wasn't clear to me what the purpose was of the transport options. I assumed it was meant to skip SSL certificate validation, but the argument error seemingly came from `gen_tcp` and I wasn't able to find any reference to the `verify` option in Erlang's documentation. 

Would you welcome extra test cases? I'm preparing them for my own project, but since they're so generic they could easily be ported to wind. One thing I noticed is that the test included with Wind passed because it was using `connect()` directly, thus bypassing the transport_opts.

**Comment by bfolkens** [comment]
Yes that would be fantastic, thanks!

**Comment by xanderificnl** [comment]
I just noticed that you already added extra tests, and Mint's test suite is also very comprehensive, if I happen to encounter something or think of another test case, I'll send a PR!
