### ISSUE TITLE
Crash when network is lost

### ISSUE THREAD

**Issue by darkblueorange** [bfolkens/wind#3]
First of all thanks for this library. 
I'm not using it directly, but through another one, [W3WS](https://github.com/stocks29/w3ws). 

It seems to work globally fine, except when network is lost. 
I spelunked a bit and arrived to this understanding:

Underlying `Mint` library raises, but `Wind` does not handle it in some places. 

In wind `client.ex` (Module `Wind.Client`) `handle_info/2` receives a damaged state (disconnected or closed) and fails in handling the error on this line:
`{:ok, conn, websocket, data} = Wind.decode(conn, ref, websocket, message)`
a `case do` can deal with some other possibility like `{:error, conn, reason} ->` but then I wouldn't know if it should be ignored (`{:noreply, state}` or a legitimate stopping reason `{:stop, {:error, message}, state}`)

Besides if we go through the `decode/4` function of `Wind` Module we can see another failing error handling case: 
`with {:ok, conn, [{:data, ^ref, data}]} <- Mint.WebSocket.stream(conn, message),
 ... do ...`
(no `else`, and this is actually the first place failing when networks fades away)

Finally when this function crashes (`Wind.decode/2` first, but if we fix it, `Wind.Client.handle_info/2` will also crash at some point), the associated GenServer reboots and attempts to launch a new connection through `handle_continue/2` in `Wind.Client` Module. 
If network is still down, there is another fail (through the infamous `:nxdomain`), and we end up in sending `{:stop, {:error, conn, reason}, state}` to the GenServer. 
It could be good to fail (I would personally have preferred a `ping` spaced more and more to attempt after n*i seconds with i growing over time), but the thing is that when the GenServer stops it crashes the whole application. 

I'm not familiar with all the GenServer communication and possible events handling (maybe using `Process.send_after(self(), ...` is a way), so I could not propose some PR in a reasonable time. 

Bug is easy to reproduce, just switch off your wifi, or close your laptop for a minute :slight_smile: 

Thanks again

**Comment by bfolkens** [comment]
Thanks @darkblueorange for the details - much appreciated.  Can you include a stack trace or two with the whatever cases you can capture?

**Comment by darkblueorange** [comment]
There is nothing specific to the implementation, so any subscription with a down network should produce the same result (hopefully):

```elixir
[debug] ping
[debug] pong
[debug] sending request %{id: 39, params: ["0x5a53f9b47d4359e51122ce2546d6ed86"], method: :eth_unsubscribe, jsonrpc: "2.0"}
[debug] sending request %{id: 40, params: [:logs, %{address: "0x849F9e7BF31bB7a038A6cB3B69030203a31fAD91", topics: []}], method: :eth_subscribe, jsonrpc: "2.0"}
[debug] received response %{"id" => 39, "jsonrpc" => "2.0", "result" => true} for request %{id: 39, params: ["0x5a53f9b47d4359e51122ce2546d6ed86"], method: :eth_unsubscribe, jsonrpc: "2.0"}
[debug] received response
%{id: 39, params: ["0x5a53f9b47d4359e51122ce2546d6ed86"], method: :eth_unsubscribe, jsonrpc: "2.0"}
%{"id" => 39, "jsonrpc" => "2.0", "result" => true}
[debug] destroyed subscription: 0x5a53f9b47d4359e51122ce2546d6ed86
[debug] received response %{"id" => 40, "jsonrpc" => "2.0", "result" => "0x4fcb0d2108b7bb3b297c08df9171dd93"} for request %{id: 40, params: [:logs, %{address: "0x849F9e7BF31bB7a038A6cB3B69030203a31fAD91", topics: []}], method: :eth_subscribe, jsonrpc: "2.0"}
[info] tracking subscription 0x4fcb0d2108b7bb3b297c08df9171dd93 for #PID<0.4092.0>
**>> all good until now <<**

**>> cutting down network <<**
[error] GenServer #PID<0.4093.0> terminating
** (MatchError) no match of right hand side value: {:error, %Mint.HTTP1{host: "eth-sepolia.g.alchemy.com", port: 443, request: nil, streaming_request: nil, socket: {:sslsocket, {:gen_tcp, #Port<0.227>, :tls_connection, :undefined}, [#PID<0.4097.0>, #PID<0.4096.0>]}, transport: Mint.Core.Transport.SSL, mode: :active, scheme_as_string: "https", requests: {[], []}, state: :closed, buffer: "", proxy_headers: [], private: %{scheme: :wss, mode: :active, extensions: [], sec_websocket_key: "TBRzdCzb1mz7xvSsmoY34w==", websockets: [#Reference<0.1400374153.2749890561.28369>]}, log: false}, %Mint.TransportError{reason: :closed}, []}
    (w3ws 0.3.0) lib/w3ws/rpc.ex:169: W3WS.Rpc."handle_info (overridable 2)"/2
    (stdlib 5.0.2) gen_server.erl:1077: :gen_server.try_handle_info/3
    (stdlib 5.0.2) gen_server.erl:1165: :gen_server.handle_msg/6
    (stdlib 5.0.2) proc_lib.erl:241: :proc_lib.init_p_do_apply/3
Last message: {:ssl_closed, {:sslsocket, {:gen_tcp, #Port<0.227>, :tls_connection, :undefined}, [#PID<0.4097.0>, #PID<0.4096.0>]}}
State: %{opts: [uri: %URI{scheme: "wss", userinfo: nil, host: "eth-sepolia.g.alchemy.com", port: 443, path: "/v2/{ALCHEMY_KEY}", query: nil, fragment: nil}], conn_info: {%Mint.HTTP1{host: "eth-sepolia.g.alchemy.com", port: 443, request: nil, streaming_request: nil, socket: {:sslsocket, {:gen_tcp, #Port<0.227>, :tls_connection, :undefined}, [#PID<0.4097.0>, #PID<0.4096.0>]}, transport: Mint.Core.Transport.SSL, mode: :active, scheme_as_string: "https", requests: {[], []}, state: :open, buffer: "", proxy_headers: [], private: %{scheme: :wss, mode: :active, extensions: [], sec_websocket_key: "TBRzdCzb1mz7xvSsmoY34w==", websockets: [#Reference<0.1400374153.2749890561.28369>]}, log: false}, #Reference<0.1400374153.2749890561.28369>, %Mint.WebSocket{extensions: [], fragment: nil, private: %{}, buffer: ""}}, base_rpc: %{id: 40, pending: %{}, subscriptions: %{"0x25fffeb1ab5d8581069bea15c64eab50" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.94931>}, "0x28ad6d840bf42a8df0c78e29e9925b61" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.106780>}, "0x2a58edc490f22c272515687e89498107" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.125885>}, "0x4c0cb5774e17e3fb74ccc3033a445b85" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.40689>}, "0x4cdaf7d67a3b1fb3cc117a76ebc3d184" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.132969>}, "0x4e43209eee22c77aee44bd590bef767f" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.69859>}, "0x4fcb0d2108b7bb3b297c08df9171dd93" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.145223>}, "0x5a53f9b47d4359e51122ce2546d6ed86" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.138926>}, "0x6012ea0fb683649d355b38fa8d390a9f" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.82285>}, "0x8c5e96832ce570c4a2b2e9d65bc04812" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.34439>}, "0x8e94bbb1a993d6ca08019a2be5f9f443" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.88635>}, "0x94cf9ca5cbd46d8e4e355de4b1d761fb" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.28423>}, "0x9592590b83d6e1b2a09e8094b552e729" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.46468>}, "0x967fd601421b23f57ffb8f109d243619" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.52297>}, "0xa253af4a127a21ddeced386d96376779" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.58156>}, "0xc68c733e17d7f2c8c610553134d24b72" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.113046>}, "0xcbdb6590ae75673319b9f02b4be7e17d" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.100943>}, "0xd91c2fcf74d2b4244a8438a575cc5f23" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.119477>}, "0xe1da82b107c420022b72ddf041688e18" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.76055>}, "0xf309de3b376c6da40beb0d2d60fe1148" => {#PID<0.4092.0>, #Reference<0.1400374153.2749890561.63935>}}, connected?: true, queued: []}}
**>> here is the second error after GenServer restart if I'm not mistaken <<**
[debug] Connecting to wss://eth-sepolia.g.alchemy.com/v2/{ALCHEMY_KEY}
[error] GenServer #PID<0.4165.0> terminating
** (stop) {:error, %Mint.TransportError{reason: :nxdomain}}
Last message: {:continue, :connect}
State: %{opts: [uri: %URI{scheme: "wss", userinfo: nil, host: "eth-sepolia.g.alchemy.com", port: 443, path: "/v2/{ALCHEMY_KEY}", query: nil, fragment: nil}], conn_info: nil}
[debug] Connecting to wss://eth-sepolia.g.alchemy.com/v2/{ALCHEMY_KEY}
[error] GenServer #PID<0.4167.0> terminating
** (stop) {:error, %Mint.TransportError{reason: :nxdomain}}
Last message: {:continue, :connect}
State: %{opts: [uri: %URI{scheme: "wss", userinfo: nil, host: "eth-sepolia.g.alchemy.com", port: 443, path: "/v2/{ALCHEMY_KEY}", query: nil, fragment: nil}], conn_info: nil}
[...]
[info] Shutting down 1 sockets in 1 rounds of 2000ms
[info] Shutting down 1 sockets in 1 rounds of 2000ms
[notice] Application solid_flow exited: shutdown
```

Unfortunately the real line in error is not shown because of the multiples \_\_using\_\_ macro imported.

**Comment by bfolkens** [comment]
@darkblueorange I added some additional error handling and a `handle_error/2` callback for the user to customize.  If everything works well for you I'll push a new version.

**Comment by darkblueorange** [comment]
Hi @bfolkens 
Sorry for the delay, I tested the new version, and it's easy now to catch the network connection issue!
If you can tag a new version so we can retrieve it from a tag and not from git url pointing towards main it would be awesome. 

P.S. On a side note, I don't know if it would be a good practice to identify all your `Logger.debug` with some `"[WIND] ..."`
Thanks again for the great work 🙏

**Comment by darkblueorange** [comment]
Not immediately related: I can see in the log one ping for three pongs. Is it wanted?
I feel like network loss take a bit of time to be detected. I did put ping_timer to 10 seconds, but it takes a lot more time to raise when I cut the network.

**Comment by bfolkens** [comment]
> Hi @bfolkens Sorry for the delay, I tested the new version, and it's easy now to catch the network connection issue! If you can tag a new version so we can retrieve it from a tag and not from git url pointing towards main it would be awesome.
> 
> P.S. On a side note, I don't know if it would be a good practice to identify all your `Logger.debug` with some `"[WIND] ..."` Thanks again for the great work 🙏

You should be able to include the context of the log message in your logger config.

**Comment by bfolkens** [comment]
> Not immediately related: I can see in the log one ping for three pongs. Is it wanted? I feel like network loss take a bit of time to be detected. I did put ping_timer to 10 seconds, but it takes a lot more time to raise when I cut the network.

Hrm, that shouldn't be the case.  Do you want to take a look and see if you can locate, perhaps submit a patch?  I'm really tied up with work next few weeks so it could be a bit.  Feel free to open a new ticket if you can repro and submit code for a minimal case.
