### ISSUE TITLE
exiting client

### ISSUE THREAD

**Issue by dch** [bfolkens/wind#4]
how does one cleanly terminate a connection on:

- success
- failure (i.e. return error)

is there a specific way to handle it, or just use normal GenServer terminations?

**Comment by bfolkens** [comment]
Wind is more or less a boilerplate wrapper around `Mint.Websocket`, so in general that library's documentation is a good reference point.

For example, if you receive a frame of `{:close, _code, _reason}` then you'd want to `Mint.HTTP.close(conn)` to exit gracefully.  This is covered here in more detail: https://hexdocs.pm/mint_web_socket/Mint.WebSocket.html#t:frame/0-close-frames

To monitor GenServer exits, yes, you'd probably want to handle via the GenServer `terminate/2` callback.  If you really want to trap all exits, you could opt for a `Process.monitor` and handle a `:DOWN` message.

Happy to take a look at a PR though if you find more boilerplate in your own code and would like to include it in the library.
